// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Referral_Management.Api.Models;

#nullable disable

namespace Referral_Management.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626092337_AddReferralGroupId")]
    partial class AddReferralGroupId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Referral_Management.Api.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__719FE48841AC8957");

                    b.HasIndex("UserId");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int>("AppointmentStatusId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCC2B14E1A90");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReferralId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Appointment", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AppointmentHistory", "dbo");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("Referral_Management.Api.Models.AppointmentStatus", b =>
                {
                    b.Property<int>("AppointmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AppointmentStatusId")
                        .HasName("PK__Appointm__A619B6601A1B0C4C");

                    b.ToTable("AppointmentStatus", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ActionUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId")
                        .HasName("PK__AuditLog__EB5F6CBD94C788C4");

                    b.HasIndex("ActionUser");

                    b.HasIndex("ReferralId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("FacilityId")
                        .HasName("PK__Facility__5FB08A742A3E2073");

                    b.HasIndex("HospitalId");

                    b.ToTable("Facility", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.GlobalNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__GlobalNe__3214EC073DA2D8CE");

                    b.ToTable("GlobalNetwork", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<int?>("GlobalNetworkId")
                        .HasColumnType("int");

                    b.Property<string>("HeadOfficeAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.HasKey("HospitalId")
                        .HasName("PK__Hospital__38C2E5AFC2390EF5");

                    b.HasIndex("GlobalNetworkId");

                    b.ToTable("Hospital", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("InsuranceProviderName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("InsuranceStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PatientAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PrimaryFacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__970EC366A7C00568");

                    b.HasIndex("PrimaryFacilityId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Mrn" }, "UQ__Patient__C797E1BCFABB0ADF")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByCoordinatorId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationFacilityId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("FromSpecialistId")
                        .HasColumnType("int");

                    b.Property<int>("OriginFacilityId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReferralGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferralReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ReferralStatusId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrgencyLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("ReferralId")
                        .HasName("PK__Referral__A2C4A9666E2BECE4");

                    b.HasIndex("CreatedByCoordinatorId");

                    b.HasIndex("DestinationFacilityId");

                    b.HasIndex("FromSpecialistId");

                    b.HasIndex("OriginFacilityId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReferralStatusId");

                    b.HasIndex("SpecialtyRequestId");

                    b.HasIndex("UrgencyLevelId");

                    b.ToTable("Referral", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ReferralHistory", "dbo");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralAssignment", b =>
                {
                    b.Property<int>("ReferralAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralAssignmentId"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int?>("FromSpecialistId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ReassignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<int>("ToSpecialistId")
                        .HasColumnType("int");

                    b.HasKey("ReferralAssignmentId")
                        .HasName("PK__Referral__CB0E6EB4434F6A6A");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("FromSpecialistId");

                    b.HasIndex("ReferralId");

                    b.HasIndex("ToSpecialistId");

                    b.ToTable("ReferralAssignment", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralCoordinator", b =>
                {
                    b.Property<int>("ReferralCoordinatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralCoordinatorId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReferralCoordinatorId")
                        .HasName("PK__Referral__E8AC3BF889C263C2");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("ReferralCoordinator", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralStatus", b =>
                {
                    b.Property<int>("ReferralStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ReferralStatusId")
                        .HasName("PK__Referral__2B43ECB50DF40A6E");

                    b.ToTable("ReferralStatus", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1AFFEEFE46");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ShiftBlock", b =>
                {
                    b.Property<int>("ShiftBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftBlockId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.HasKey("ShiftBlockId")
                        .HasName("PK__ShiftBlo__82DDFDA0ABAF7148");

                    b.ToTable("ShiftBlock", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Specialist", b =>
                {
                    b.Property<int>("SpecialistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialistId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftBlockId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SpecialistId")
                        .HasName("PK__Speciali__7092086E77734F8A");

                    b.HasIndex("FacilityId");

                    b.HasIndex("ShiftBlockId");

                    b.HasIndex("UserId");

                    b.ToTable("Specialist", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.SpecialistSpeciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Speciali__3214EC070FB6AB5A");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex(new[] { "SpecialistId", "SpecialtyId" }, "UQ_SpecialistSpecialty")
                        .IsUnique();

                    b.ToTable("SpecialistSpecialities");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SpecialtyId")
                        .HasName("PK__Specialt__D768F6A87E566C6F");

                    b.ToTable("Specialty", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.UrgencyLevel", b =>
                {
                    b.Property<int>("UrgencyLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrgencyLevelId"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UrgencyLevelId")
                        .HasName("PK__UrgencyL__0CA733F96A5C242C");

                    b.ToTable("UrgencyLevel", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C16B0C76E");

                    b.HasIndex("FacilityId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534F470BC56")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserHistory", "dbo");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("Referral_Management.Api.Models.VwAppointmentDetail", b =>
                {
                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .IsUnicode(false)
                        .HasColumnType("varchar(201)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("ReferralReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialistName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .IsUnicode(false)
                        .HasColumnType("varchar(201)");

                    b.ToTable((string)null);

                    b.ToView("vw_AppointmentDetails", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.VwCoordinatorRequestedReferral", b =>
                {
                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationFacility")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("DestinationFacilityId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OriginFacility")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .IsUnicode(false)
                        .HasColumnType("varchar(201)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable((string)null);

                    b.ToView("vw_Coordinator_RequestedReferrals", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.VwSpecialistAssignedPatient", b =>
                {
                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .IsUnicode(false)
                        .HasColumnType("varchar(201)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable((string)null);

                    b.ToView("vw_Specialist_AssignedPatients", (string)null);
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Admin", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Appointment", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.AppointmentStatus", "AppointmentStatus")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_AppointmentStatus");

                    b.HasOne("Referral_Management.Api.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Patient");

                    b.HasOne("Referral_Management.Api.Models.Referral", "Referral")
                        .WithMany("Appointments")
                        .HasForeignKey("ReferralId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Referral");

                    b.HasOne("Referral_Management.Api.Models.Specialist", "Specialist")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecialistId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Specialist");

                    b.Navigation("AppointmentStatus");

                    b.Navigation("Patient");

                    b.Navigation("Referral");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.AuditLog", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.User", "ActionUserNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActionUser")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_User");

                    b.HasOne("Referral_Management.Api.Models.Referral", "Referral")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ReferralId")
                        .HasConstraintName("FK_AuditLog_Referral");

                    b.Navigation("ActionUserNavigation");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Facility", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.Hospital", "Hospital")
                        .WithMany("Facilities")
                        .HasForeignKey("HospitalId")
                        .IsRequired()
                        .HasConstraintName("FK_Facility_Hospital");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Hospital", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.GlobalNetwork", "GlobalNetwork")
                        .WithMany("Hospitals")
                        .HasForeignKey("GlobalNetworkId")
                        .HasConstraintName("FK_Hospital_GlobalNetwork");

                    b.Navigation("GlobalNetwork");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Patient", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.Facility", "PrimaryFacility")
                        .WithMany("Patients")
                        .HasForeignKey("PrimaryFacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Patient_Facility");

                    b.HasOne("Referral_Management.Api.Models.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Patient_User");

                    b.Navigation("PrimaryFacility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Referral", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.ReferralCoordinator", "CreatedByCoordinator")
                        .WithMany("Referrals")
                        .HasForeignKey("CreatedByCoordinatorId")
                        .HasConstraintName("FK_Referral_Coordinator");

                    b.HasOne("Referral_Management.Api.Models.Facility", "DestinationFacility")
                        .WithMany("ReferralDestinationFacilities")
                        .HasForeignKey("DestinationFacilityId")
                        .HasConstraintName("FK_Referral_DestinationFacility");

                    b.HasOne("Referral_Management.Api.Models.Specialist", "FromSpecialist")
                        .WithMany("Referrals")
                        .HasForeignKey("FromSpecialistId")
                        .IsRequired()
                        .HasConstraintName("FK_Referral_FromSpecialist");

                    b.HasOne("Referral_Management.Api.Models.Facility", "OriginFacility")
                        .WithMany("ReferralOriginFacilities")
                        .HasForeignKey("OriginFacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Referral_OriginFacility");

                    b.HasOne("Referral_Management.Api.Models.Patient", "Patient")
                        .WithMany("Referrals")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Referral_Patient");

                    b.HasOne("Referral_Management.Api.Models.ReferralStatus", "ReferralStatus")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferralStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Referral_ReferralStatus");

                    b.HasOne("Referral_Management.Api.Models.Specialty", "SpecialtyRequest")
                        .WithMany("Referrals")
                        .HasForeignKey("SpecialtyRequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Referral_Specialty");

                    b.HasOne("Referral_Management.Api.Models.UrgencyLevel", "UrgencyLevel")
                        .WithMany("Referrals")
                        .HasForeignKey("UrgencyLevelId")
                        .IsRequired()
                        .HasConstraintName("FK_Referral_UrgencyLevel");

                    b.Navigation("CreatedByCoordinator");

                    b.Navigation("DestinationFacility");

                    b.Navigation("FromSpecialist");

                    b.Navigation("OriginFacility");

                    b.Navigation("Patient");

                    b.Navigation("ReferralStatus");

                    b.Navigation("SpecialtyRequest");

                    b.Navigation("UrgencyLevel");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralAssignment", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.ReferralCoordinator", "AssignedByNavigation")
                        .WithMany("ReferralAssignments")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("FK_ReferralAssignment_AssignedBy");

                    b.HasOne("Referral_Management.Api.Models.Specialist", "FromSpecialist")
                        .WithMany("ReferralAssignmentFromSpecialists")
                        .HasForeignKey("FromSpecialistId")
                        .HasConstraintName("FK_ReferralAssignment_FromSpecialist");

                    b.HasOne("Referral_Management.Api.Models.Referral", "Referral")
                        .WithMany("ReferralAssignments")
                        .HasForeignKey("ReferralId")
                        .IsRequired()
                        .HasConstraintName("FK_ReferralAssignment_Referral");

                    b.HasOne("Referral_Management.Api.Models.Specialist", "ToSpecialist")
                        .WithMany("ReferralAssignmentToSpecialists")
                        .HasForeignKey("ToSpecialistId")
                        .IsRequired()
                        .HasConstraintName("FK_ReferralAssignment_ToSpecialist");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("FromSpecialist");

                    b.Navigation("Referral");

                    b.Navigation("ToSpecialist");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralCoordinator", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.Facility", "Facility")
                        .WithMany("ReferralCoordinators")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_ReferralCoordinator_Facility");

                    b.HasOne("Referral_Management.Api.Models.User", "User")
                        .WithMany("ReferralCoordinators")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ReferralCoordinator_User");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Specialist", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.Facility", "Facility")
                        .WithMany("Specialists")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Specialist_Facility");

                    b.HasOne("Referral_Management.Api.Models.ShiftBlock", "ShiftBlock")
                        .WithMany("Specialists")
                        .HasForeignKey("ShiftBlockId")
                        .HasConstraintName("FK_Specialist_ShiftBlock");

                    b.HasOne("Referral_Management.Api.Models.User", "User")
                        .WithMany("Specialists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Specialist_User");

                    b.Navigation("Facility");

                    b.Navigation("ShiftBlock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.SpecialistSpeciality", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.Specialist", "Specialist")
                        .WithMany("SpecialistSpecialities")
                        .HasForeignKey("SpecialistId")
                        .IsRequired()
                        .HasConstraintName("FK_SpecialistSpecialities_Specialist");

                    b.HasOne("Referral_Management.Api.Models.Specialty", "Specialty")
                        .WithMany("SpecialistSpecialities")
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("FK_SpecialistSpecialities_Specialty");

                    b.Navigation("Specialist");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.User", b =>
                {
                    b.HasOne("Referral_Management.Api.Models.Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Facility");

                    b.HasOne("Referral_Management.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Facility");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.AppointmentStatus", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Facility", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("ReferralCoordinators");

                    b.Navigation("ReferralDestinationFacilities");

                    b.Navigation("ReferralOriginFacilities");

                    b.Navigation("Specialists");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.GlobalNetwork", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Hospital", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Referral", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("ReferralAssignments");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralCoordinator", b =>
                {
                    b.Navigation("ReferralAssignments");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ReferralStatus", b =>
                {
                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.ShiftBlock", b =>
                {
                    b.Navigation("Specialists");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Specialist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ReferralAssignmentFromSpecialists");

                    b.Navigation("ReferralAssignmentToSpecialists");

                    b.Navigation("Referrals");

                    b.Navigation("SpecialistSpecialities");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.Specialty", b =>
                {
                    b.Navigation("Referrals");

                    b.Navigation("SpecialistSpecialities");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.UrgencyLevel", b =>
                {
                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("Referral_Management.Api.Models.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("AuditLogs");

                    b.Navigation("Patients");

                    b.Navigation("ReferralCoordinators");

                    b.Navigation("Specialists");
                });
#pragma warning restore 612, 618
        }
    }
}
